### ISSUE TITLE
Detecting PCIe DMA via software on the attacked computer

### ISSUE THREAD

**Issue by gcakir** [ufrisk/pcileech#107]
Since this question is asked multiple times (#70) and I am curious about this as well, I researched it a little bit and came across several resources (i.e. research papers):

"Detecting Peripheral-based Attacks on the Host Memory": https://depositonce.tu-berlin.de/bitstream/11303/4494/1/stewin_patrick.pdf

"Can Hardware Performance Counters be Trusted?": http://www.cse.chalmers.se/~mckee/papers/iiswc08.pdf

"Poster: Towards detecting DMA malware": https://www.mulliner.org/collin/publications/p857-stewin.pdf

**Comment by ufrisk** [comment]
Thanks for a good collection and some nice reads.

I'd be surprised if the timing analysis is doable in a real world scenario on a modern busy system though. If it's doable to some degree I'm guessing the indicator would be somewhat weak. There is a reason why mostly idle systems are chosen in this research.

Right now it's probably just easier and more stable to look at the PCIe configuration space for the Xilinx PCIe IP block.

**Comment by ufrisk** [comment]
I'm closing this issue due to old age.

If you're still interested in how it's possible to detect PCILeech PCIe DMA on the target computer the major gaming studios seems to put considerable effort in doing this with limited success nowdays as parts of their anti-cheats. So I would guess it to be fairly hard to detect DMA in practice.
