### ISSUE TITLE
USB3380EVB not available

### ISSUE THREAD

**Issue by meriniamjo** [ufrisk/pcileech#11]
HI,
 I was trying to implement this DMA attack. But it seems this USB3380EVB is not available anywhere(Even PP380-AB). Do you have any suggestion on an alternative ?
Would really appreciate any help.

**Comment by ufrisk** [comment]
Hi,
Yeah, I know the HW is hard to get by after my defcon talk. You could check with bplus when/if they are going to restock. Otherwise MFactors might have a few units still in stock at:
http://www.mfactors.com/usb3380evb-usb3380-evaluation-board/
http://www.mfactors.com/pp3380-ab-usb3380-ab-evaluation-board/
The ExpressCard to mini-PCIe and PCIe to mini-PCIe adapters seems to be sold out tho; but substitures for those ones can be found on ebay.
Please let me know how it goes.
Good Luck and Happy Hunting =)
//Ulf

**Comment by meriniamjo** [comment]
Thank you for the immediate reply. The links have the products available.

Thanks!

**Comment by Snook123** [comment]
Is it possible to do it with other hardware too, cause it is nearly impossible to get the piece in europe

**Comment by ufrisk** [comment]
PCILeech only supports the PP3380 and USB3380-EVB hardware unfortunately.

But BPlus have it in stock. They ship fast from Taiwan. It usually takes 2-3 days for an order to show up at my doorstep in Europe.

**Comment by LennyPenny** [comment]
The price is through the roof though - I hope they go below $100 again soon

**Comment by ufrisk** [comment]
Unfortunately they raised the price to $195 just after my def con talk. I wouldn't have too high hopes for the price to come down, not unless anyone else decides to start selling boards, the chip itself is around $15 list price...

**Comment by MarkVerhyden** [comment]
I've decided to delve into this but not having any luck finding a populated board.  Any other sources you could suggest?

**Comment by ufrisk** [comment]
Unfortunately not. Asking around for a used one might be your best bet.

I'm trying to get this to work on a FPGA dev board as well, but that might take time, if I manage to complete it at all.
