### ISSUE TITLE
Windows 10 KMD load not working

### ISSUE THREAD

**Issue by whatsgoingon1177111** [ufrisk/pcileech#121]
Victim: Windows 10 1909 (AMD Ryzen Processor)
Board: M.2 Screamer (Flashed with pcileech with custom device id)

Error:
pcileech.exe kmdload -kmd win10_x64

KMD: Failed. Error reading or interpreting PT.
PCILEECH: Failed to load kernel module.

**Comment by whatsgoingon1177111** [comment]
Sorry, i should have stated that my goal is to load my own unsigned driver into the OS.

**Comment by whatsgoingon1177111** [comment]
I solved the first part of this by disabling fast boot. Now my only issue is 100% chance of BSOD when loading the driver.

**Comment by ufrisk** [comment]
is it the kmdload that is bluescreening or the driverload module?

the driverload module is pretty old; I haven't tested it in the last windows version or two, it may be that it's no longer working as desired.

if it's the kmdload that is bluescreening; the win10_x64 usually does that on the more latest versions of Windows; the `pcileech.exe kmdload -kmd win10_x64_2` usually works better in those cases.

since you get a bluescreen I suspect that the ScreamerM2 is working just fine; i.e. it's able to read and write to memory.

**Comment by whatsgoingon1177111** [comment]
The kmdload works perfecly, thats driverload module specifically is bluescreening the pc 100% of the time. Everything else works perfect on the screamer after disabling fast boot. Any ideas why it isnt working on the latest version of win10?

**Comment by whatsgoingon1177111** [comment]
I also can confirm that the driver itself works, i can load it fine with a public manual mapper i found online. Its definitely the driverload function of pcileech.

**Comment by njbrown09** [comment]
+1 also have this issue

**Comment by ufrisk** [comment]
Yeah, it doesn't surprise me one bit unfortunately, I haven't updated that in quite a while and Microsoft is changing stuff around all the time so it probably stopped working a couple of Windows version back.

Manually mapping it into the kernel is probably the best way to go; I should try to add that to PCILeech, but right now I need to finish up some other issues before I'm able to do more contributions unfortunately.

**Comment by whatsgoingon1177111** [comment]
Dang, i really needed this :(. Ill keep looking at this until its resolved, thanks for the help!

**Comment by ufrisk** [comment]
I think this should be working now. Please let me know if it's not (please also re-open the issue in that case). Good Luck :)
