### ISSUE TITLE
Major Instability on X470 Ryzen.

### ISSUE THREAD

**Issue by whatsgoingon1177111** [ufrisk/pcileech#125]
Im having major issues stability issues on my ryzen 9 3900x and m2screamer. I constantly get bad tlp's and such, and initializing is extremely random when it wants to work. The screamer is very finnicky to get working too.

**Comment by whatsgoingon1177111** [comment]
I also should note, i tested my pcileech hardware on an intel system and its working  flawlessly.

**Comment by whatsgoingon1177111** [comment]
Just discovered something new, dumping memory ALWAYS fails at or around 87%. I tried 4 different ram sticks too....

**Comment by ufrisk** [comment]
I'm aware. But you have to understand PCILeech is my hobby project. I have put a lot of personal time and money into this already.

I also have perfectly working computers (Intel). I just don't have a need for a Ryzen right now outside of PCILeech research. I'm not very keen on purchasing a new Ryzen 9 3900X system for $1500-isch to try figure out what's going on.

Over the years I've received less than $200 in total contributions money wise. All from very nice individuals - Thank You :) And Screamer HW from Lambda. I also had a 1yr, now expired, MSDN from MS a few years back as a thanks for the TotalMeltdown vulnerability. Other than that I've received in total $0.0 worth of money/goods for PCILeech work. Hardly noone amongst the big and small corporations are giving anything back to this project. Since it's open source it's free and you don't have to do that, and it's never something I expected. But bying a lot of different hardware cost a lot of money when it all adds up over time ...

I even switch jobs last year to try to be able to work a bit with this during working hours; but even that now seems to be very unlikely due to legal issues.

While this have been, and still it, interesting for me doing this research and building these tools, you (and the corporations of the world) cannot expect me to also spend all my money on getting all the new hardware just so that you can get this for free.

---

But this is on my todo list, who knows, maybe I'll be able to look into this a couple months down the road.

**Comment by ufrisk** [comment]
Can you please try to re-flash your ScreamerM2 with v4.4 of the FPGA bitstream found at https://github.com/ufrisk/pcileech-fpga to see if it resolves your issues.

I suspect it may resolve some issues, but not quite all, since I still have to do fixes in software on the PCILeech side of things as well. The FPGA should be much more stable though. Can you please report back how it went?

**Comment by ufrisk** [comment]
Please try the release just released. This should now be fixed. For best stability I would suggest dumping with: `pcileech.exe dump -v -device fpga -memmap auto` on your Ryzen system.

Since this should now be fixed I'm closing the issue. If you should still experience any issues please let me know and re-open the issue.
