### ISSUE TITLE
VmmWinInit_TryIntialize: Initializtion Failed

### ISSUE THREAD

**Issue by Nigesi** [ufrisk/pcileech#139]
Hey Ulf, much appreciate your work, thanks so much. 

I try to solve this issue, but i have no clue what I'm doing wrong. I update to the version 4.6 and still got that issue

The secruity options in my bios are disabled and I'm working on a Ryzen 1600x. 

Any clue?  

![Test](https://user-images.githubusercontent.com/68186362/87244927-4fdca500-c441-11ea-8929-c58ca31c9c2e.PNG)

**Comment by ufrisk** [comment]
Yes, bitstream changes to the fpga isn't enough to fix it completely on AMD. I also have to make a small change to the MemProcFS.

You can't read the whole memory block of lower 1MB in VmmWinInit_DTB_FindValidate(); it will have to be changed to it only read between addresses in the below image. Note that is the new code that will be published; if making changes you'll have to adjust it to the older reading function.

I'm publish this as soon as I have a bunch of other features ready; aiming for August/September some time.

![image](https://user-images.githubusercontent.com/18221464/87245587-b87a5080-c446-11ea-9bb0-f76db2b0d649.png)

**Comment by Nigesi** [comment]
thanks for helping me out. I'll wate for the fix

**Comment by ufrisk** [comment]
Please try the release just released. This should now be fixed. For best stability I would suggest starting MemProcFS with: `MemProcFS.exe -device fpga -memmap auto` on your Ryzen system. Note that I have only tested it on a 3900X but I believe other Ryzens should behave the same.

Since this should now be fixed I'm closing the issue. If you should still experience any issues please let me know and re-open the issue.
