### ISSUE TITLE
Flashing documentation

### ISSUE THREAD

**Issue by iTestAndroid** [ufrisk/pcileech#14]
I have this board:
http://www.hwtools.net/Adapter/USB3380EVB.html

And this:
http://www.hwtools.net/jpg/USB3380-AA%20EVK_1.jpg

And this:
http://www.hwtools.net/jpg/USB3380EVB-PE3B_1.jpg

And this:
http://www.hwtools.net/jpg/USB3380-AB_EVK-RC_1.jpg

I tried to flash PCILeech using USB3380EVB board alone connected via USB with no luck. Then I attached the USB3380EVB to PCIe converter and plugged it into PCIe port, no luck. 
What am I missing? What's the correct connection combination to flash the PCILeech into USB3380EVB?

**Comment by ufrisk** [comment]
Hi,

If you purchased this:
http://www.hwtools.net/jpg/USB3380-AB_EVK-RC_1.jpg

it won't work. It's a dev kit for the USB3380 in "root complex" mode. If you use the mini-PCIe card from this kit it won't work since it's also configured as "root complex"; which unfortunately is useless for PCILeech.

-----

The mini-PCIe board, and the adapters, below are the correct ones, provided that you actually purchased the USB3380-EVB (for $195 on the hwtools site) and that you don¨t use the mini-PCIe board from the root complex kit above...

I have this board:
http://www.hwtools.net/Adapter/USB3380EVB.html

And this:
http://www.hwtools.net/jpg/USB3380-AA%20EVK_1.jpg

And this:
http://www.hwtools.net/jpg/USB3380EVB-PE3B_1.jpg

You should mount the mini-PCIe (USB3380-EVB) on one of the adapters, insert it into the PCIe or ExpressCard slot and then flash it.

Flashing can be done in 64-bit Windows 10 or 64-bit Linux. You must be administrator/root. Flashing must be done from the OS running on the physical hardware. Flashing from inside a virtual machine is not possible. Flashing over USB is also not possible.

If successful the blue LED should lit up brightly.

**Comment by iTestAndroid** [comment]
I unmounted the USB3380-EVB from main complex board, so that should work. I also have the ExpressCard board but I don't have a PC or laptop with ExpressCard port. So I think I am only missing ADP board. aDP is sold out in their website, but I am going to buy this:
https://www.amazon.com/gp/aw/d/B00L9OB8AW/

Would it work? I just want to flash PCILeech and then I can do rest with USB/ExpressCard board/thunderbolt. Right?

Thanks for replying

**Comment by ufrisk** [comment]
Please let me know how it goes. If you have the USB3380-EVB bundled with the USB3380-AB_EVK-RC kit then I suspect it might not work. Their site says it's the USB3380-EVB-R (strapped in root complex mode). But I haven't tested that one, so I don't know. I've only tested the one they sell for $195 now (used to be $78)

Any cheap PCIe to miniPCIe adapter will do. eBay sell a lot of them for mini-PCIe wifi boards - they will work fine if you unscrew the plate... 
http://www.ebay.co.uk/itm/300Mbps-DESKTOP-PC-WIRELESS-WIFI-PCI-E-NETWORK-ADAPTER-CARD-802-11-N-2ANTENNAS-/282215736724

Once flashed it should be possible to do evilness over PCIe/Thunderbolt, provided that you have the necessary adapters.

**Comment by iTestAndroid** [comment]
Thank you. Will keep you posted. Also just ordered mini pcie to PCI. Also FYI, in this PDF:
http://www.bplustech.com/PDF/USB3380EVB_brief.pdf

It shows "USB3380-AB EVK-RC Contents" as USB3380, just like the original one. Will try with mini pcie to pcie and ADP adapter and keep you posted about it. Happy holidays :)

**Comment by iTestAndroid** [comment]
Hey

I tested it with USB3380-EVB-R and it never worked. I just replaced it with USB3380-EVB.

Now when I have USB3380-EVB connected to ADP adapter, directly connected to mini-PCIe port of my PC.
When I try to install driver in Windows, it throws me driver installation failed error and no detail.
When I do it in Linux, it just gives me "Operation not permitted" (root user)

Any ideas?

**Comment by ufrisk** [comment]
Thanks for letting me know about the USB3380-EVB-R.

I will assume you're connecting the mini-PCIe USB330-EVB card to a regular PCIe slot by using the ADP adapter. I also assume you're not trying to flash it from the actual physical machine - not from within a virtual machine (sorry for bringing this up, but others actually tried to flash from within VMWare before...)

In Windows, are you running the installer program `PCILeechFlash_Installer.exe` as Administrator on Windows 10 64-bit or Windows 8.1 64-bit? It is expected to fail on 32-bit platforms and/or on Windows 7/8.0.

About the Linux module, I haven't seen that error myself, it seems like you aren't allowed to load kernel modules. That may be the case if you are booting with "Secure Boot". Also google says some people had more success with modprobe instead of insmod. But I haven't tried it myself really.

Please let me know how it goes.

//Ulf

**Comment by ufrisk** [comment]
hrm, it seems like you are actually able to load the kernel module in Linux (I should read the whole post before posting a reply) and it will fail flashing (or at least verifying the flash image somehow). Can you try it a couple of times? Also try it after a reboot? 

If it still fails, are you able to try it on a different computer? I noticed that some older hardware some times have problems reading memory. Haven't noticed anything with the flashing though.

Please let me know how it goes. If it still fail you I might have to send you a custom linux flash module with more error logging... but if it would work after a reboot, or on another computer it would be easier.

**Comment by iTestAndroid** [comment]
Hey Ulf,
Thanks for detailed answer.
Yes, USB3380 connected to ADP, ADP connected directly to motherboard's mini PCIe slot, I don't use VM for flashing, it's main OS, I run Windows flash installer as Administrator and Linux one with sudo/root.

What's best way to verify firmware write? Maybe it's written? Should it turn on the blue LED right after flash?
I don't have a laptop with ExpressCard port also don't have Apple device. So I'm trying to get an ExpressCard to USB adapter to try a linux and windows laptop with. It would work that way, right?

I'm going to try modprobe and I'm going to add some verbose printf stuff in code to see where and how it fails and I'll report back. Thank you

**Comment by iTestAndroid** [comment]
Update: I tried to debug Flash installer and Windows version, seems like it was path and certificate issue etc. I got it to Install the driver, then it says completed, but I don't see Blue LED turning on. It does have 2 orange and one green on. When I reboot the PC, Green and blue LED is on but blue LED is not that bright. Is there a way to confirm if it's working or not without a laptop with ExpressCard port for now? I'll be getting one soon

**Comment by ufrisk** [comment]
If successful the blue should be brightly lit. If it's just dimly lit it's not it. It will light up after a successful flash & verify (write and read).

Easiest way of testing it is probably to connect the device by USB to the computer and try dumping some memory (after the usb driver is installed).

In the Linux driver, are you able to change the line that says: `#define DEVICE_WAIT_TIME   10` to `#define DEVICE_WAIT_TIME   50` and recompile it and try again?

**Comment by iTestAndroid** [comment]
I changed to 50, no change. Then I changed to 100, still nothing. Same error in /var/log/syslog and same message "operation not permitted" in console. Any ideas?

**Comment by iTestAndroid** [comment]
When I turn on PC while ADP + USB3380 is plugged into Mini PCIE port, I see only green LED is lit along with blue LED, but it's dim, not bright.
Then if I go to Windows or Linux and try to Flash it, two orange lights are lit brightly along with green. In windows, I don't get error messages. But in Linux I get "operation not permitted".
Now I turn off PC and turn back on and only green + dim blue is on. Meaning not worked, right?

**Comment by iTestAndroid** [comment]
I did some more debugging by adding lots of printk to Linux flash code, it fails here:
if(*(unsigned int*)(pbar0 + OFFSET_PCIREG_VEN_DEV) != 0x338010B5 && *(unsigned int*)(pbar0 + 		OFFSET_PCIREG_VEN_DEV) != 0x16BC14E4) {
and returns -1 and

**Comment by ufrisk** [comment]
The LEDs can look a bit different, that is normal behaviour.

You are trying to flash the USB3380-EVB mini-PCIe board right? Mounted on the ADP PCIe to mini-PCIe adapter, which is mounted in a regular PCIe port in your machine? In that config there aren't really any jumpers or similar to change.

I know some PC's do have problems with the hardware though; I haven't seen it when flashing though, just when doing the DMA attacks. I'll check out the flash program with the most recent ubuntu tomorrow, I've only tested it up to 16.04 as is now.

One additional thing you could try in Windows, if you solved the certificate issue, is to remove, or set to 0, the registry entry "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\WUDF\Services\PCILeechFlash\disable". The setup program will set this key before it exits. This is so that the installed driver shouldn't reflash a hardware on every reboot or new insertion.

I suspect it won't solve your problem though; and that trying it on a different computer might be the best way forward. As a last resort you also have some flashing tools from PLX/Broadcom, but they require registration on their site...

**Comment by iTestAndroid** [comment]
"which is mounted in a regular PCIe port" ?

I have USB3380-EVB connected to ADP which gives me mini PCIe port ready to be attached to PC. So I plug it into mini-PCIe port of my motherboard, no?

I also tried to compile USB3380 SDK and tried to flash SLOTSCREAMER but it keeps reporting that eeprom not found when I run eep. What am I missing here? I wrote the PCILEECH firmware to a bin file and was trying to flash it just like SLOTSCREAMER, it would work and have same effect, right?

I'm missing something obvious, I'm sure, but can't find it

**Comment by iTestAndroid** [comment]
Also can you explain "Easiest way of testing it is probably to connect the device by USB to the computer and try dumping some memory (after the usb driver is installed)."

Assume I just want to test my own PC, can I connect USB3380EVB to ADP and ADP to mini-PCIe, then use the USB cable to try to read memory of my own machine?

I want to know how can I do some basic tests, maybe firmware is loaded. But I don't have ExpressCard port on my PC or laptop. Any alternative? Thank you

**Comment by ufrisk** [comment]
Yes, you can connect it to USB on the same computer to which you already have it connected to with PCIe.

You should flash `firmware_pcileech.bin` instead of the slotscreamer firmware if using the PLX tools method. I must say that the "The PLX chip reports no EEPROM present" looks worrying though. I've purchased lots of USB3380-EVB's and never had a hardware problem though.

You are using:
`http://bplus.com.tw/jpg/ADP_1.jpg` together with `http://bplus.com.tw/jpg/USB3380EVB_1S.jpg` this one right?

I'd say the best option would be to try flashing it on a different computer if possible. I'll also look into flashing on more recent linux versions tomorrow to verify that it still works. (flasher is only tested with ubuntu 16.04 and even older versions of debian and kali).

**Comment by iTestAndroid** [comment]
Yes.

I'm using http://bplus.com.tw/jpg/ADP_1.jpg together with http://bplus.com.tw/jpg/USB3380EVB_1S.jpg  and connected to PCIe and mini-PCIe ports of my motherboard. Both cases, I get "The PLX chip reports no EEPROM present".

Also when it's connected to PCIe or Mini-PCIe and I connect USB port to same computer, it's like nothing is attached to USB. I have Android driver installed on my machine, but no new USB device is ever detected. I did installed INF file using Add legacy hardware, I see Android ADB interface with excalamation point in Android devices category, I think it's fine?

**Comment by ufrisk** [comment]
It's not successfully flashed then. The USB interface is disabled by default, flashing is required to enable it.

**Comment by iTestAndroid** [comment]
Do you think I have bad USB3380-EVB? What's different between 2380 and 3380? Would 2380 work too?

**Comment by ufrisk** [comment]
I haven't tried the 2380. My guess is that it won't work out of the box, but that it would be possible to make it work given some coding, at USB2 speed.

 I guess there is a possibility that your hardware is broken, the error message from the PLX tools seems to indicate this. I'd still try flashing the hardware on a different computer before giving up on it though. I've ordered plenty of USB3380-EVBs and I never had a problem.

**Comment by iTestAndroid** [comment]
Just before giving up to re-confirm everything I do is same as yours:

- We compile PLX SDK
- We run the driver: bin/driver_load Svc
- We open the PlxCM app: samples/PlxCM/App/PlxCm

Here when you type eep in your machine with real USB3380, you get results, you don't get eeprom not found etc. Is that correct?

**Comment by ufrisk** [comment]
It first failed on me after I installed the SDK and loaded the driver

>eep
Error: EEPROM access not supported for this device

But after a reboot it works fine, including the eep command (after loading the driver).

**Comment by iTestAndroid** [comment]
Can you explain the reboot to me? So I plug it, I boot into Linux, I try to flash, it won't work, now I reboot, do it again and it should work?

**Comment by iTestAndroid** [comment]
Also please explain to me your hardware,  do you also use ADP? If so do you put ADP in mini pcie or pcie? If not, what you use.

**Comment by ufrisk** [comment]
I use ExpressCard->PE3B->USB3380.

I don't know why it worked after the reboot and not before, found it to be a bit strange, it's not a behaviour I noticed before.

The ADP adapter can only be put into a PCIe slot. If you use a mini-PCIe slot you have to put the USB3380-EVB in there without the adapter...

**Comment by iTestAndroid** [comment]
You can flash firmware using ExpressCard? 

I think I am confusing mini pcie and pcie. As far as I see, I can't plug usb3380 directly to any of the ports on my motherboard, but when I connect it to ADP, almost all slots would work.

Am I missing anything?
Since you said ExpressCard and pe3b, can I use ExpressCard to USb for a computer that doesn't have ExpressCard port to flash?

**Comment by ufrisk** [comment]
You can't flash over USB. Flashing has to be done over PCIe unfortunately :\ You're not able to try flashing it on a different computer?

Flashing should work over "standard" PCIe as well though. It's not like it's only possible to flash it with ExpressCard. Others have successfully flashed it via PCIe and mini-PCIe.

**Comment by iTestAndroid** [comment]
I don't know why I have the problem. Unfortunately I don't have any other PC with pcie port. No laptop with ExpressCard port. I am kinda sure my usb3380 is not faulty. Don't know what I am missing. Did you ever flash with ADP + Pcie port?

**Comment by ufrisk** [comment]
I never flashed it with the ADP before, so I just tried it - and it worked the very first time on Win10.

I don't see any reason why USB3380EVB => PE3B => ExpressCard => Sonnet Thunderbolt 2 Adapter => ( Apple TB2 to TB3/USB-C adapter) => Thunderbolt to PC wouldn't work even tho I haven't tried it myself. I don't have my NUC with USB-C/TB3 here at the moment so I can't try it. I would guess you would need to set the TB3 security mode to "Legacy" in BIOS if you have such a setting tho. Thats what I had to do on my NUC to get it working with DMA without the OS blocking it.
