### ISSUE TITLE
Footprints of pcileech hardware in user-space or kernel

### ISSUE THREAD

**Issue by SeldaBagcan** [ufrisk/pcileech#15]
Is it possbile to detect pcileech hardware(i mean USB3380) doing dma operations from inside of the victim's operating system(Windows in this case) or kernel?

_Sincerely_

**Comment by ufrisk** [comment]
The device shows up in device manager as "Broadcom SD-card". If one wish to be more stealthy it's possible to alter the firmware and reflash it with a different device id. It's not possible to avoid the device getting detected, but it's possible to change what it is detected as.

When reading and writing memory without using the kernel module no additional artifacs are left in the system.

When inserting the kernel module, reading and writing memory, this:
- allocates 8192 bytes of memory for the kernel module
- creates a new kernel thread
- allocates 16MB bytes of memory as buffer
This is visible from kernel mode if you know what you're looking for. Otherwise not. It's not directly visible from user mode, but if one look at statistics one can see that 16MB more memory is allocated, and that a kernel thread is created. I believe this is very well hidden within normal fluctuations tho. If memory is dumped by the user it's also possible to detect PCILeech, but normal forensics tools such as Volatility won't detect it.

If you are executing different kernel implants, such as spawn cmd.exe additional artifacts may be left in the system.

Even after "unloading" the kernel module with kmdexit the 8192 bytes of memory will still be allocated and filled with PCILeech code. If there is a need for it I could change it so this memory is cleared as well.

**Comment by SeldaBagcan** [comment]
Thanks for the detailed reply and apology for my late comment. In this case i am looking into bypassing anti-cheat softwares with pcileech and read memory freely so i can build a hardware cheating solution for myself(i already have some programming background but i also started learning about electronics with this idea) . I still have some concerns before buying the device itself because it got pretty expensive very quick! 200+ USD is not really inexpensive in my economical situation and country)

How much latency occurs while reading? Is it around a few miliseconds? 
I know its not directly about pcileech but are there any cheaper alternatives for dma memory reading purpose?(I heard about inception firewire but sadly i couldnt manage to get it working on my old-ass asus laptop with firewire port and a pci-e firewire card)

It still amazes me how computers are vulnerable to smart people and i really appreciate your work on this subject.

_Best wishes._

**Comment by ufrisk** [comment]
it's in the 10ms range I think.

Another option for your use case might be to code a kernel module and insert it in the target system. This will avoid latency. If you wish to map user process memory and read/write from it please check out https://github.com/ufrisk/pcileech/blob/master/pcileech_shellcode/wx64_pscreate.c .

Also there are other ways to get code into the kernel, for example via a vulnerable driver. You might want to check out those options for a more low cost approach. But I guess those approaches might be a bit more less stealthy for your use case.

**Comment by signal-5** [comment]
I guess SeldaBagcan wants modify an in game value like HealthPoints while the game is running.
As a gamer I would recommend to first search in a full dump after the value and when you have found it save the position and the offset of the value. You can do it with my tool [https://github.com/signal-5/pcileech/blob/master/pcileech_tools/search_offset.pl](https://github.com/signal-5/pcileech/blob/master/pcileech_tools/search_offset.pl). Then the question is, how long time does it take to _write_ to that offset? Or do you want to read before the write to be sure you are writing over the right memory? Don't answer in this thread as I guess it should be used for "Issues" ;)
The cost has more that doubled sins ufrisk did his Vegas presentation. Every hacker and government agency need one of their own...

**Comment by Snook123** [comment]
Is it possible to read and write that the host system won't recognise it?
Even if there is a driver that is going to detect reads and writes at least when they are executed by the system itself

**Comment by ufrisk** [comment]
yep, if accessing memory without using an implanted kernel module.

**Comment by Snook123** [comment]
Is there a hardware out there which suports DMA with 16GB memory.
Ofc it should be programable. Do you know one?

**Comment by ufrisk** [comment]
I'm not aware of such a hardware, except for more expensive FPGA boards.

**Comment by ufrisk** [comment]
Closing question due to old age.
