### ISSUE TITLE
test with usb3380_evb fail

### ISSUE THREAD

**Issue by shaobingyang** [ufrisk/pcileech#153]
Hi,
I did a test with usb3380 evb, and failed. Test is in Windows 10 Ver 1903. 
Win-usb driver's installation failed with an error (This device cannot start. (Code 10) The specified request is not a valid operation for the target device.)
Usb3380 driver's installation failed with an error (This device cannot start. (Code 10)  {Incorrect Network Resource Type} The specified device type (LPT, for example) conflicts with the actual device type on the remote resource. )
So did I do it in the wrong way, Or what can I do next to do a usb3380 test? 
![Capture01](https://user-images.githubusercontent.com/2509443/96544877-f4d90a80-12d9-11eb-8698-a7adfef94533.JPG)
![Capture02](https://user-images.githubusercontent.com/2509443/96544880-f60a3780-12d9-11eb-85ab-1b843d03efad.JPG)
![Capture03](https://user-images.githubusercontent.com/2509443/96544881-f6a2ce00-12d9-11eb-9228-7c5854d1ebed.JPG)
![Capture04](https://user-images.githubusercontent.com/2509443/96544883-f73b6480-12d9-11eb-9a94-65ac8f6e4f83.JPG)
![Capture00](https://user-images.githubusercontent.com/2509443/96544885-f86c9180-12d9-11eb-822b-5bf2c9a68c59.JPG)

**Comment by ufrisk** [comment]
It probably work better if you right click install on the inf file instead of going through and manually selecting hardware.

![image](https://user-images.githubusercontent.com/18221464/96641289-c9c7d880-1324-11eb-833b-229319820c57.png)

Just tried on latest Google USBdriver in a fresh install Windows (2004 release) but I don't think that should matter. It's probably a driver install thing.

Please let me know if you get it to work.

**Comment by shaobingyang** [comment]
I tried usb_driver_r12-windows.zip in win2004, tested installation using inf. Installation was successful judging from the prompts, but nothing changed in device manager. No new devices found. Installation of USB3380 using inf was the same. Still, I cannot flash USB3380 evb. Does usb3380 work on well on your machine? Did I miss something? Could you show me your testing environment?
![Capture01](https://user-images.githubusercontent.com/2509443/96671202-e18a7580-1393-11eb-8f37-dd2e473d2431.PNG)
![Capture02](https://user-images.githubusercontent.com/2509443/96671208-e3543900-1393-11eb-8a8d-1cc2fd9053ff.PNG)

**Comment by ufrisk** [comment]
The installation of the Google USB driver is for PCILeech to be able to communicate with the USB interface.

The USB interface of the USB3380 is however disabled by default and the device would need to be flashed before it's enabled.

You would need to flash the device first as given in the flash instructions here: https://github.com/ufrisk/pcileech/blob/master/usb3380.md If it fails with the Windows flash tool (which have nothing to do with the Google USB driver) please try flashing on Linux. Flashing needs to be done while the USB3380 is inserted into PCI Express of the flash system. It's not possible to flash from the USB side (since the USB is disabled by default).

**Comment by shaobingyang** [comment]
^_^, actually I am working on this.
