### ISSUE TITLE
Is the USB3380 board necessary

### ISSUE THREAD

**Issue by deadly-platypus** [ufrisk/pcileech#184]
Given the current hardware availability issues, I was wondering if the separate USB3380 hardware is necessary.  I have a victim PC with both Thunderbolt 3 and USB 3.2 USB C ports, and an attacker PC with both ports as well.  Would it be possible to just use the hardware I have on hand to use PCILeech.  I tried using it, but I didn't get far, with PCILeech reporting `PCILEECH: Failed to connect to the device.`  I am new to this kind of work, but am pretty experienced with systems development in general.  If it is a matter of opening and using a device file if there is hardware available, then I'd be happy to add that support in!

**Comment by ufrisk** [comment]
You'd need hardware to perform DMA attacks. Just having a Thunderbolt<->Thunderbolt connection between the two PCs won't work.

The USB3380 is very limiting though. I don't recommend it. Better get FPGA based hardware from https://github.com/ufrisk/pcileech-fpga  unfortunately most are sold out currently due to the chip crisis.

**Comment by deadly-platypus** [comment]
Thanks for the response!
