### ISSUE TITLE
 System is not entering S3 (Sleep) state with PCIe Leech USB 3380 Card connected

### ISSUE THREAD

**Issue by sridhaleech** [ufrisk/pcileech#192]
Hi Team,

System is not entering S3 (Sleep) state in Yocto OS with PCIe Leech USB 3380 Card connected.

While performing S3 state observed “Write error: device or resource busy” Attached error of screenshot.

![image](https://user-images.githubusercontent.com/97678866/168952480-bc2cd2ed-b91b-4d4f-8bc4-f59adfc53a7a.png)

Using command for S3 (Sleep): echo mem > /sys/power/state

Cloud you help to solve this issue, due this issue we unable to S3 resume testing in Yocto OS .

Isolation :

We have tried without PCI leech Card connected  and Its S3 working fine .

Thanks,
Sridhar

**Comment by ufrisk** [comment]
This may be an issue with the USB3380. To be honest I haven't looked into it. It may or may not be possible to change this behavior via flash.

Main use case is that people connect it to the system for a short while and perform a DMA attack and then disconnect it. Also FPGA hardware is much more capable than the USB3380 so its not so much used nowdays.

Please understand that this is an open source project, I do this on my free time. This is also a very small issue for the general user base (even though it may be serious for you). I will not be looking into this due to time reasons.

If it's really important I could possibly look into it against a paid consultancy, but I don't know if it's possible to resolve. It's probably cheaper to get an FPGA board like the [Screamer](https://shop.lambdaconcept.com/) than paying for some hours of consultancy with unknown result.

I'll close this issue as no-fix.

**Comment by sridhaleech** [comment]
Thanks for your valuable update.
Okay noted .

FPGA board like the [Screamer](https://shop.lambdaconcept.com/)

which best model to use ? any suggestion for FPGA .
( And i'm going to my Target system Liunx and windows 10 )

i will try to buy and test it.
