### ISSUE TITLE
Regarding PCI leech USB3380 Driver installation

### ISSUE THREAD

**Issue by sridhaleech** [ufrisk/pcileech#194]
In the "Limitations/Known Issues"

Some Linux kernels does not work. Sometimes a required symbol is not exported in the kernel and PCILeech fails.

 - What it means by “required symbol is not exported in the kernel”  ?

**Comment by ufrisk** [comment]
The kernel exports certain symbols (functions) to other kernel modules.

Sometimes the exported symbols (functions) change and if PCILeech is relying on one of them and it's no longer exported it will stop working.

you can most often view these in `/proc/kallsyms` file on linux (as root).

**Comment by sridhaleech** [comment]
we ran the /proc/kallsyms file on system.

inthat which one is the PCI leech symbol ?

**Comment by ufrisk** [comment]
There is quite a lot of work involved in this. I've been mostly focused on Windows as of late since that seems to be more popular amongst the users (and also I'm more familiar with it).

I'll try to update the Linux modules in the coming months to keep them more up-to-date. But it will probably be some time off.

**Comment by ufrisk** [comment]
I'm closing this issue due to old age.
