### ISSUE TITLE
PCIe leech USB3380 : How to write memory in efi shell page and how to confirm the written memory ? 

### ISSUE THREAD

**Issue by sridhaleech** [ufrisk/pcileech#196]
Hi,
How to write memory in efi shell page and how to confirm whether the data written to memory , is there verify command  ?

Our goal is --> Need to do write some data into the direct DRAM. what is the procedure ? when we write some data what is the system behavior ?

Kindly advise this .
 
Device : PCIe leech USB3380 EV  and Test need to do "efi" mode (edk shell page )

Thanks advance.

**Comment by ufrisk** [comment]
I'm not quite sure what you're trying to achieve here, but since UEFI memory space is usually mapped 1:1 with the physical memory space I supposed you can use the pcileech write command to write the memory and then the pcileech display command to read (verify the memory) if you use the pcileech binary.

The same would be possible using the [LeechCore](https://github.com/ufrisk/LeechCore) API.

---

If you already got code execution via one of my pre-built kmdload implants for UEFI you'd have to compile a custom pcileech module/implant for it that you can then ask the already implanted code to load. Example how to do such an implant is in the code. A good example would be the [textout plugin](https://github.com/ufrisk/pcileech/blob/master/pcileech_shellcode/uefi_textout.c).

**Comment by sridhaleech** [comment]
Hi ,

i'm able to write the command ,but i can't display the written range of physical memory .

Getting some "Failed reading memory address" attached screenshot.

![image](https://user-images.githubusercontent.com/97678866/175854098-61bd08bf-f3c9-4e02-b801-1b6eca36d167.png)
=======================
if don't mind, can you pls help me below .

How to find the KMD address in windows and linux ? and how to load the -kmd address to WIndows /Linux OS  ?

**Comment by ufrisk** [comment]
I'm really sorry, but please understand that this is an open source project. I spend a lot of free time on this already as things are. I try to provide reasonable support to all kinds of questions. I do this completely for free.

Please understand that I'm not interested in providing unlimited support for all kinds of questions spending a lot of time all for free. Generally you'd be better off getting an FPGA device (such as the screamer) which is more stable and more versatile than the usb3380. Also please try to look through some conference presentations and check some blog posts from me and others before asking for a lot of free support.

If you're still stuck and wish to get a lot of support I can offer paid support as well.

**Comment by ufrisk** [comment]
I'm closing this issue due to old age.
