### ISSUE TITLE
Request help for PCIe FPGA 64 bit leech device model with support OS - Help required

### ISSUE THREAD

**Issue by sridhaleech** [ufrisk/pcileech#199]
Hi,

We are planning to buy new FPGA 64 bit leech device for our testing. which support for latest OS (Ubuntu,Windows 10 and Yocto) .

For our testing , To target physical memory read and write .

Last time ,we had one FPGA Spartan SP605 device and still we are unable to make it work in our testing system.Because our system is windows 10 OS. 
And FPGA Spartan SP605 device is very old model. and this card not working with Windows 10 OS.
(Looks to be OS not support issue ).

Notes : Our goal is to test with client system (target)  with Ubuntu,Windows 10 and Yocto loaded.

Now, can you pls suggest the PCIe FPGA 64bit card extract model, version and other required accessories and testing files ?

So can purchase card and others .

We struggling lot to enable FPGA 64 bit card. if you provide the above all details, It may helpful us.

Thanks advance.

Regards/ Sridhar D

**Comment by ufrisk** [comment]
If you already have the SP605 it will work just fine once flashed even though I don't target it with firmware updates anymore (due to the arcane horrible dev environment).

If wanting something newer there is always the AC701 from Xilinx, but the better choice here is probably the [Screamer PCIe Squirrel](https://github.com/ufrisk/pcileech-fpga/blob/master/PCIeSquirrel) from LambdaConcept.

Good Luck and best wishes with this!

Ulf

**Comment by ufrisk** [comment]
I'm closing this issue due to old age.
