### ISSUE TITLE
cheat-engine + pcileech

### ISSUE THREAD

**Issue by uk0** [ufrisk/pcileech#223]
hi bro  you Can integrate pcileech and cheat-engine so that it can be used, cheat-engine directly operates fpga to process memory and dump memory, ？

**Comment by uk0** [comment]
Is it possible to add a GUI to pcileech to query and modify the process PID memory

**Comment by ufrisk** [comment]
I created the PCILeech and MemProcFS projects for security research and forensics. I did not know it would become popular with cheats.

It's one thing to create and maintain a project which is ntended for security research and forensics and merely used for cheats and one thing to actively create software that is directly targeted at cheats (such as a CE integration).

There has been a cheat engine integration floating around here on Github. It now seems to be removed (including forks). I don't know the reason for this, but regardless if the removal is due to legal action or Github policy it's not a risk I'm willing to take. Thanks for understanding.


The PCILeech API (MemProcFS project) have APIs for reading and writing process memory. Creating a CE integration or a GUI is certainly possible (it would even be quite easy). I'm however not personally planning on doing so. If someone else is up to the task then go for it!

**Comment by uk0** [comment]
thx ：） 

It may be easier or cheaper to use ce to conduct security detection and analysis of games in China.

**Comment by ufrisk** [comment]
I agree that having a CE integration would be good. I don't know what happened to the previous one that was floating around on Github. It's just that I'm not the one that will do that integration.

I would thing it to be fairly straightforward to do such an integration if using the MemProcFS APIs.

**Comment by eXskill** [comment]
No integration required. It is enough that Cheat Engine can read vmem files without loading them into memory. Any HEX editor opens such files correctly, but CE does not support this. You need to write to the author CE ^^
