### ISSUE TITLE
how to getasynkkeystate with pcileech on windows 11?

### ISSUE THREAD

**Issue by fortnitebott** [ufrisk/pcileech#225]

**Comment by ufrisk** [comment]
Microsoft have changed how the gafAsyncKeyState works on the most recent Windows 11 22H2.

I haven't looked into how it's done now. I've kinda been hoping someone else would reverse how it's working now since I've been quite busy. I see that the export itself is gone from `win32kbase.sys` though and that it's been replaced with some C++ mangled name `?gafAsyncKeyState@@3V?$SGDKEYBOARDgafAsyncKeyState@PEAE@@A`. But it's probably not the same.

Also there is another export _GetAsyncKeyState that looks interesting, but it's probably a function.

But as I mentioned I haven't looked into this. Please let me know if you should solve it somehow.

**Comment by fortnitebott** [comment]
I found it:

win32ksdg.sys!gSessionGlobalSlots

UINT64 Session1_UserSessionState = Read<UINT64>(Read<UINT64>(Read<UINT64>(gSessionGlobalSlots)));

UINT64 gafAsyncKeyState = Session1_UserSessionState + 0x3690;

but how to get and read this with pcileech?

**Comment by ufrisk** [comment]
This would require you to have the the DLLs for microsoft debug symbols alongside vmm.dll. dbghelp.dll and symsrv.dll.

```C
ULONG64 va_win32ksdg = 0xfff...;
ULONG64 va_gSessionGlobalSlots = 0;
CHAR szModuleName[MAX_PATH] = { 0 };
BOOL fLoadOK = VMMDLL_PdbLoad(hVMM, 4, va_win32ksdg, szModuleName);
BOOL fSymbolOK = VMMDLL_PdbSymbolAddress(hVMM, szModuleName, "gSessionGlobalSlots", &va_gSessionGlobalSlots );
```

I'm not completely sure PID 4 will work all the way though, it may be that you'd need to use a CSRSS PID instead.

I should add an example about how to use the debug symbols.

Please let me know how it goes.

**Comment by ufrisk** [comment]
And it looks like quite a convoluted way of doing it, but if it works it's all ok I guess.

If I follow the pointers (I might have missed something) in your example I see that the Session1_UserSessionState points to a big pool allocation with pool header 'Sgaa'. If this is correct it might be easier to retrieve it that way. I have two on my test system so it's probably correct that it's the UserSessionState.

**Comment by fortnitebott** [comment]
![image](https://user-images.githubusercontent.com/60422445/223416764-3ceb6d3a-b7f1-43f7-80f0-4fb5c1d3a04a.png)
![image](https://user-images.githubusercontent.com/60422445/223416802-ddad5071-225b-4ee2-b189-38966d0b0a6d.png)

**Comment by fortnitebott** [comment]
![image](https://user-images.githubusercontent.com/60422445/224047964-356ea386-3204-47e9-afad-e6df456c1d48.png)
![image](https://user-images.githubusercontent.com/60422445/224048017-daee2b88-1e7c-46f7-b85a-4130efc9b000.png)
![image](https://user-images.githubusercontent.com/60422445/224048088-f5f6f82b-2e2c-4619-b9f6-7e8c93ad00e4.png)

**Comment by ufrisk** [comment]
There is something not working with the debug symbol load. Does it print any on the console if you add the startup-parameters: `    "-printf", "-loglevel", "symbol:7"   `

---

An alternative that may be easier in your case would be to follow the example for the pool map:

https://github.com/ufrisk/MemProcFS/blob/4c5626a6939a6d868db9b69f346f0b9fd42bba11/vmm_example/vmmdll_example.c#L1265

Just search for pool header: `Sgaa` instead of pool header: `TcpE` in the example. In my win11 test machine there seems to be two `Sgaa` objects in the big pool (probably one per session) this would correspond with your large memory allocation where you use the offset in.

**Comment by fortnitebott** [comment]
I use startup-parameters. They don't write anything to the console

**Comment by ufrisk** [comment]
How did it go with this issue, did you have any success?

**Comment by ufrisk** [comment]
Since I haven't gotten any answers I'm assuming this issue was resolved so I'm closing the issue. If it's not resolved let me know.
