### ISSUE TITLE
PCILEECH WITH LAPTOP?

### ISSUE THREAD

**Issue by viperr86** [ufrisk/pcileech#230]
Hey,
I Wanna test your PCILEECH stuff, but im not sure what i can do with laptop, im heard about M2-TO USB, but do i need M2 dma for this or i can use any DMA ?
Thanks

**Comment by ufrisk** [comment]
I don't know what you mean by M2 to USB. I haven't heard about such a thing.

M2 ports generally carry PCI Express though (which is a pre-requisite of doing DMA with PCILeech). With a proper adapter cable you're likely to be able to do DMA from your M2 port.

If your laptop have other DMA capabilities I can't say, it would depend on the laptop and which ports it have.

USB is not DMA capable. Thunderbolt are however.

**Comment by viperr86** [comment]
It only has USB-C other than the normal things, not Thunderbolt port so thats the thing.

so i guess its not possible for me to use DMA for me in any other way than maybe open up my laptop and check the motherboard ports or?
Thanks again

**Comment by ufrisk** [comment]
If that is the case it looks like that unfortunately. Thunderbolt (or OCuLink) is required to do DMA over external connections.

Either that or M2 ports under your back cover. You may find a teardown at youtube or a manual if you don't wish to open it up yourself to have a look. But it would most likely be quite cumbersome of doing DMA on the laptop this way since you'd most likely have to unmount something, like the wifi board, to be able to fit a cable to PCILeech. Also if you have the Screamer you'd have to power it with external power as well via additional adapters.
