### ISSUE TITLE
Unable to connect to device: FPGA

### ISSUE THREAD

**Issue by ArcticSlayy** [ufrisk/pcileech#238]
Hello, so whenever I attempt to use PCILeech via the command line interface it does not connect. I know it's not the cable as I am able to use the memprocfs library in Python perfectly fine to be able to read/write memory. What can I do? I've attempted to run as admin, I know the middle LED blinks.

**Comment by ArcticSlayy** [comment]
![image](https://github.com/ufrisk/pcileech/assets/64766174/d7a977c7-9691-4edd-a717-0aa832106cfd)

I am getting this, I do have the FTD3XX.DLL in my PCILeech_files. The tool next to it is th Atomic's benchmark tool to see if my card is reading/writing, and it's speed.

**Comment by ufrisk** [comment]
I'm sorry, but I'm not able to support games hacking since I'd prefer not to get involved.

The one to the left is working though, and the one to the right explicitly says in the error message that the DLL file is unable to load. If it's there it may be the wrong bitness on it, i.e. Win32 (wrong) instead of x64 (correct) from the link I sent you earlier on. Or just copy required dll file from the other tool.

Best of luck with this though, and I hope you'll resolve the issue. Let's hope it's the above issue.

**Comment by ArcticSlayy** [comment]
Hello @ufrisk I apologize if you meant that was game hacking. I meant to use it as an example to show it's properly reading as a PoC.

**Comment by ArcticSlayy** [comment]
I wish to use it for the findevil and forensic analysis like the example you did live with the reading of our password, or reading of live processes in my mounted drive.
