### ISSUE TITLE
Failed to read protected program memory

### ISSUE THREAD

**Issue by Monday-Leo** [ufrisk/pcileech#245]
I'm reading the game's memory and at the beginning everything works fine. But after about ten minutes, some memory reads fail. I think it may be that the game's protection mechanism has played a role. After I re-run the program, the memory can be read normally again, but it fails again after ten minutes. What is the problem and how can it be solved? It is the same situation when I use Cheat Engine software, can DMA break through this limitation?

**Comment by ufrisk** [comment]
Hi, if your game starts to protect itself against DMA its not much you can do about it _after_ it have enabled its protections.

I prefer that game hacking is not discussed on my Github since I didn't create my tools for it and I wish to keep my distance to it.

I know that there have been discussions for specific games such as Valorant recently. You can google around and find some discussions about it on some cheat related forums.

If you come across a non-games related issue / bug I'd be happy to fix it as soon as possible.

But for this issue I'd have to forward you to the more specialized forums discussing this.
