### ISSUE TITLE
Loading Driver Via DMA

### ISSUE THREAD

**Issue by MrCoInSanity** [ufrisk/pcileech#246]
Hello, I was wondering if its possible to load a driver via DMA? Thanks in advance!

**Comment by ufrisk** [comment]
It's currently not supported straight out of the box.


You could transfer a file to the target file system (supported) and spawn a shell (supported) and thru that shell load the driver from disk. This would be the currently supported way.

You could temporarily disable the signing enforcement (if desirable).

You could manual-map the driver into the target kernel (if you have kernel code execution).


I suspect  you'd wish to do the manual map somehow or have it implemented in PCILeech since it won't touch disk of the target system. But it's a bit of work to add it.

**Comment by MrCoInSanity** [comment]
That solves my question, thank you for the information!
