### ISSUE TITLE
PCIleech expected behavior with Enable Pre-Boot DMA Support BIOS option.

### ISSUE THREAD

**Issue by jbishtx** [ufrisk/pcileech#259]
What's the expected behavior When "Enable Pre-Boot DMA Support" is set as "Disabled" & "Enabled"?

NOTE: Enable Pre-Boot DMA Support BIOS option we can find these days in Dell, HP laptops.

**Comment by ufrisk** [comment]
Long answer: Please understand that this is mostly a hobby project, I'm making very little money from this project. I also work a normal job so I don't have terribly much time to further research things. Also, I'm not too keen on purchasing a lot of vendor specific hardware to research vendor specific settings. Due to the above constraints I've been focusing on general issues rather than vendor specific issues.

Short answer: I don't know.

Maybe someone else here would know this though? To me it looks like an interesting setting so it would be nice to know if someone has an answer :)

**Comment by jbishtx** [comment]
Got it. Thank for responding though.
