### ISSUE TITLE
AMD 5800x3D

### ISSUE THREAD

**Issue by eyehack84** [ufrisk/pcileech#262]
Will this work with a 5800X3D processor, iv heard its best on Intel. Iv been seeing things about the Captain DMA Board designed for AMD, thank you in advance.
https://www.aliexpress.us/item/3256805392595470.html?spm=a2g0o.detail.1000014.92.3cbe417do9i5jp&gps-id=pcDetailBottomMoreOtherSeller&scm=1007.40050.362094.0&scm_id=1007.40050.362094.0&scm-url=1007.40050.362094.0&pvid=ee6cc812-8fe8-4687-9db0-ce9426be4175&_t=gps-id:pcDetailBottomMoreOtherSeller,scm-url:1007.40050.362094.0,pvid:ee6cc812-8fe8-4687-9db0-ce9426be4175,tpp_buckets:668%232846%238108%231977&pdp_npi=4%40dis%21USD%21386.90%21193.45%21%21%212820.00%21%21%40210313e916983592357926450ebb1d%2112000033624711771%21rec%21US%21%21AB#nav-description

**Comment by ufrisk** [comment]
I list the devices the project supports at https://github.com/ufrisk/pcileech-fpga

And then there are many different compatible devices elsewhere such as the one you link. They are not associated with my project though and I'm unable to give support on them.

If you decide to get one of those devices please consider sponsoring my project with a small sum here on Github if you use my software since those sellers don't contribute.

Best wishes with your DMA project 👍
