### ISSUE TITLE
USB3380 Speed only 25K

### ISSUE THREAD

**Issue by xssuser** [ufrisk/pcileech#27]
I used P15S-P15FM.2 to mPCIe Extender Board + USB3380 Evaluation Board

when i run pcileech.exe dump ,the speed only 25k-35k

Attack computer is USB3.0 and screen print

Device Info: USB330 running at USB2 speed.

why? hope help

thanks

**Comment by ufrisk** [comment]
25-35k is very slow indeed, I cannot see that you attached a screenshot, but since the output says your're running at USB2 speed there is clearly something wrong.

1) are you using an USB3 cable
2) are you connecting the USB3 cable to a USB3 port on your attacker PC? (some computer have both USB2 and USB3 ports)
3) if you are indeed connected to USB3 using an USB3 cable sometimes it might help to reboot both the target (victim) system and the attacker computer.

Please let me know how it goes.

**Comment by xssuser** [comment]
All right, the problem is solved

My USB3 port is 2.0, change to 3.0 it's OK

The Other Question

Attack system ver is win10 x64 10.0.16299.125
Target system ver is win10 x64 10.0.16299.125

i need to unlock lock screen

pcileech.exe kmdload -kmd win10x64_ntfs_20160329 -pt -sig unlock_win10x64

Is that right?
