### ISSUE TITLE
init TypeError:

### ISSUE THREAD

**Issue by Lennox7746** [ufrisk/pcileech#270]
Hello，when i running the example code ,it tell me :

>>> vmm = memprocfs.Vmm(['-device', 'C:/Dumps/WIN10-X64-1909-18363-1.mem'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Vmm.init(): Initialization of vmm failed.

How can i do for this? My systerm is win11 and the cpu is AMD R7 7840HS.
Hope the solution,thanks !

**Comment by ufrisk** [comment]
Hi,

This API call tries to initialize using a memory dump file named: `C:/Dumps/WIN10-X64-1909-18363-1.mem`.

Since you mention your system I'm assuming you wish to target the FPGA. That would be:

```Python
vmm = memprocfs.Vmm(['-device', 'fpga'])
```

or you may have to use a [memory map](https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_AMD_Thunderbolt) as well:

```Python
vmm = memprocfs.Vmm(['-device', 'fpga', '-memmap', 'C:\\Path\\To\\My\\memmap.txt'])
```

Please let me know how this goes and if the issue is resolved (then close this issue).

And best wishes with your Python DMA project :)

**Comment by Lennox7746** [comment]
I know the reason, my mother board is AMD,when i come home, I use the computer which mother board is  AMD too ( A320-pro), it not work yet,but now, I'm in my friend's home and use his computer that mother board is Intel ( Z690 ) , the same DMA board is working well，I think  I have to buy a intel mother board for using DMA board............

**Comment by ufrisk** [comment]
If you're on AMD just use the memory map approach as I linked to in the above post and things will be fine. No need to purchase new hardware.

**Comment by Lennox7746** [comment]
I'm sorry sir,I don't find the link about AMD, can you give me the link in the comment ? 
Thanks !

**Comment by Lennox7746** [comment]
And I have a question, according to the pictures in the project, my board should be LeetDMA, but I cannot find the corresponding FPGA project for LeetDMA. May I ask which FPGA project corresponds to LeetDMA?

**Comment by ufrisk** [comment]
LeetDMA is compatible with the PCIeSquirrel FPGA bitstream/project.

**Comment by Lennox7746** [comment]
OK, get it .Thank you very much !
