### ISSUE TITLE
PCIeSquirrel FPGA: ERROR: Unable to connect to USB/FT601 device [0, v0.0, 0000]

### ISSUE THREAD

**Issue by Aiden-10** [ufrisk/pcileech#272]
I received by lambda concept squirrel yesterday and everything appeared to work just fine. I then tried following your steps to change the Vendor Id, Device Id, DSN etc. that is when I began seeing the error in the title. I tried reverting back to the precompiled pcileech firmware found [here](https://github.com/ufrisk/pcileech-fpga/blob/master/PCIeSquirrel/readme.md) I am able to flash successfully following all the steps provided in LC documentation. I then try and run pcileech and get this error listed in the title.

- I see 2 LEDS (LD1 and LD3) lit up green on the board and my usb c is plugged into the data port and connected to separate laptop. 
- I get the error from running the command pcileech.exe display -min 0x1000 -device fpga -v (with FTD3XX.dll installed)

Any help would be appreciated, Thanks

**Comment by ufrisk** [comment]
It may be a bad flash or a mistake you made in your bitstream or a bad USB cable connection.

The FPGA LED should blink 3-4 times at power-on. If it does blink 3-4 times at power-on that means that the FPGA is properly flashed and that it's most likely the USB cable (it may be a bad change on your part as well, but those are rare when it comes to the USB interface).

If it does not blink at all at power-on that would mean that you have a bad flash. Try to flash the original bitstream loaded from here: https://github.com/ufrisk/pcileech-fpga/tree/master/PCIeSquirrel in that case.

**Comment by ufrisk** [comment]
Nice to see the issue was resolved.

For more info about building your own bitstream see, https://github.com/ufrisk/pcileech-fpga/blob/master/PCIeSquirrel/readme.md

It's not sufficient to change the .coe file only, the PCIe core would have to be updated in Xilinx Vivado as well.

Unfortunately I won't be able to help with this, but I wish you the best in your DMA project.

I'm closing this issue since it's now resolved.
