### ISSUE TITLE
FileVault2 password recovery on maverics

### ISSUE THREAD

**Issue by pimarplastics** [ufrisk/pcileech#28]
Dear Ufrisk,

I have successfulu run filevault password recovery on el capitan but it fails on mavericks.

It is downloading partial memory file same size as in el capitan but then it fails and computer is hangs. need restart.

**Comment by ufrisk** [comment]
I'm sorry, but I haven't been able to test this on a system running mavericks. I've only been able to test this on ElCapitan and Sierra. I heard it should be working on Yosemite as well. I simply do not have a test system for Mavericks.

The issue might requite me doing some investigations and possibly adding support for it; but this would be very hard for me to do since I simply don't have a test system.

I'm sorry about this.

**Comment by pimarplastics** [comment]
What You need to receive in order to add support ?

**Comment by ufrisk** [comment]
Having access to a test system would be the best, it would help a lot.

It would be possible to do it remote as well, I have to ask you to run a few tests and return back with the data to me, maybe it will possible to find out what the culprit is.

Please note that I cannot guarantee that we can find a solution to this, event though I believe it's very likely that we will be able to. There is a possibility that Apple changed something in FileVault in later revisions to make this bug appear (even though I think it's unlikely).

Also if we manage to resolve the issue there is a chance that the password recover attempt may fail to bad luck. It's fairly reliable as-is, but not 100% reliable.

Maybe it's best if you contact me by email at: `pcileech@frizk.net`

**Comment by ufrisk** [comment]
Since I haven't heard anything back I assume this is resolved. Closing issue.
