### ISSUE TITLE
DEVICE: FPGA: ERROR: Unable to retrieve required Device PCIe ID [4,v4.10,0000]

### ISSUE THREAD

**Issue by MojitoSama** [ufrisk/pcileech#287]
Hello,

I have recently bought the Captain75T board. It was working perfectly for 3 days, then the next morning it suddenly stopped working and showing error as below:

**DEVICE: FPGA: ERROR: Unable to retrieve required Device PCIe ID [4,v4.10,0000]
MemProcFS: Failed to connect to memory acquisition device.**

Nothing has changed after I shut down the gaming PC, and I have tried to changing PCIe slots and disabling XMP profile, but getting same error regardless.

What could be the cause of this issue? And how may I possible fix it? 
Is there a problem with the DMA board?

**Comment by ufrisk** [comment]
CaptainDMA have elected not to support this project.

They sell "compatible" boards without giving anything back in support. This is possible since this project is open source.

But please understand that due to the above I'm not keen on giving free support just so they can pocket more money in sales than they already do.

Also, I don't know much about their 75T devices, I only know they aren't directly PIN-compatible with any of the firmwares I offer in the pcileech-fpga project at: https://github.com/ufrisk/pcileech-fpga

I hope you'll be able to resolve your issue. Maybe you can ask on Discord or something like that.
