### ISSUE TITLE
read memory size and data problem

### ISSUE THREAD

**Issue by nikolindima** [ufrisk/pcileech#290]
Hello, i use Enigma X1. Target PC has 4gb memory. when try to dump it all went fine but it show 6gb size and dumping 6gb with 2gb errors pages in the end. and data in dump looks strange every time. If target PC has 8gb memory - dumping 10gb. i use pcileech.exe dump -out "d:\raw.bin" command

**Comment by ufrisk** [comment]
what do you see if you run: `pcileech.exe -device fpga dump -v` it would be interesting to know if things are normal or not. what you're describing is normal expected behavior.

A PC with 8GB RAM will have approx the address space I describe below:
0-2 GB = RAM
2-4 GB = MEMORY MAPPED PCIE DEVICES
4-10 GB = RAM

The address space in my short example is 10GB even though it only contains 8GB RAM. There is a hole in the middle used for PCI Express Devices. I strongly suspect this is what you may see.

Can you please check it out and if if it's indeed the case (and about 8GB of the 10GB is successfully dumped) then its as things should be.

**Comment by nikolindima** [comment]
run: pcileech.exe -device fpga dump -v

![2024-02-07 10 34 17](https://github.com/ufrisk/pcileech/assets/944968/f93ac31f-cdf2-4311-9aa1-d82b7f6ad672)

**Comment by ufrisk** [comment]
👍 I'm happy to see the issue is resolved. This is quite normal behavior due to the way addressing is set up on the PC platform.
