### ISSUE TITLE
M.2 Screamer Issue

### ISSUE THREAD

**Issue by imagerman999** [ufrisk/pcileech#300]
Hello,
I have recently bought an M.2 screamer board and I’m having massive issue
![image](https://github.com/ufrisk/pcileech/assets/112811234/e3ec2d11-fb5e-4ea3-9ab6-247bde168181)

I rebooted several times and tryed everything i have also the corect settings i bios im frustraded

**Comment by ufrisk** [comment]
Github issues are not really for asking general support questions. It's more for reporting issues or requesting enhancements.

But there is a guide that may be helpful: https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_DMA_Not_Working

Otherwise hop into the Discord server and ask around there: <a href="https://discord.gg/pcileech"><img src="https://discord.com/api/guilds/1155439643395883128/widget.png?style=banner3"/></a>
