### ISSUE TITLE
Specify PageDirectoryBase (DTB/CR3) in -dtb option if value if known.

### ISSUE THREAD

**Issue by Sigma12456** [ufrisk/pcileech#303]
I have a windows 11 amd system and i am frequently experiencing an issue where my dma just stops working till I restart my main system. I already am using a memmap which is called mmap.txt and is correct(verified it manually) :/

Specify PageDirectoryBase (DTB/CR3) in -dtb option if value if known.

**Comment by ufrisk** [comment]
DMA is not working for some reason. Have a look in the guide:

https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_DMA_Not_Working
https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_AMD_Thunderbolt

The Discord server may be a better place to ask questions if you don't get it to work with the above links (since it's going to be an issue with how your system is configured, and/or the usage of pcileech rather than a program bug / issue).

<a href="https://discord.gg/pcileech"><img src="https://discord.com/api/guilds/1155439643395883128/widget.png?style=banner3"/></a>
