### ISSUE TITLE
Can't read anything 

### ISSUE THREAD

**Issue by CureSaba** [ufrisk/pcileech#304]
![image](https://github.com/user-attachments/assets/8c366a13-bef5-4962-a07b-f8fdb4dd13a4)
Every page read results in Pages failed
```
WARNING: 'probe' may cause the device to stop working until a reboot on AMD or
         Thunderbolt systems and is discouraged. See link for additional info:
         https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_AMD_Thunderbolt

 Memory Map:
 START              END               #PAGES


 Current Action: Probing Memory
 Access Mode:    Normal
 Progress:       4096 / 4096 (100%)
 Speed:          81 MB/s
 Address:        0x0000000100000000
 Pages read:     0 / 1048576 (0%)
 Pages failed:   1048576 (100%)
Memory Probe: Completed.
```

**Comment by ufrisk** [comment]
Probe is super aggressive and will make DMA fail on AMD systems. That's why the warning message shows up in the text.

Follow the link described to: https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_AMD_Thunderbolt and hopefully it will resolve your issue.

Also, the Discord may be a better place to ask questions if this should not resolve the issue. This is more an issue with your system and the use of PCILeech rather than a bug in PCILeech which is the reason why I'm closing this issue.

<a href="https://discord.gg/pcileech"><img src="https://discord.com/api/guilds/1155439643395883128/widget.png?style=banner3"/></a>
