### ISSUE TITLE
DMA speeds extremely slow

### ISSUE THREAD

**Issue by csclementine** [ufrisk/pcileech#311]
PCIe squirrel - used it 2 months ago and was averaging 170 mb/s now it wont go past 35 mb/s.

Things I've tried :
- Updated bios
- Different cables, different ports, different PCs
- tried 2 different firmwares, shockz and ekknodz
- reseating the card
- cold booting / power cycling

- Both PC's are high spec so that's not an issue
- pages fail about 5% of the time but i think thats normal
- Tried a few things off this github such as the pcileech tests which pass?

Ps. let me know if you need any test ran and the output to help narrow it down.
I have no clue anymore, any help would be appreciated!

![fry](https://github.com/user-attachments/assets/8f887145-f8a9-4559-8931-cb77e5c52d32)

**Comment by ufrisk** [comment]
Speed is very consistent with USB2 speeds. Check cable, USB port in PC and that the cable is properly connected (all the way in) to the fpga board data port (sometimes the bracket has to be slightly adjusted).

I'm closing this issue though since it's not an issue with pcileech/memprocfs as such, but rather with your setup. The Discord server is a better place to ask around for issues like this unless you manage to resolve it with the above hints.

<a href="https://discord.gg/pcileech"><img src="https://discord.com/api/guilds/1155439643395883128/widget.png?style=banner3"/></a>
