### ISSUE TITLE
pcileech testmemread failed

### ISSUE THREAD

**Issue by Puzzor** [ufrisk/pcileech#41]
Hi sir,
I first flashed my 3380 on a Ubuntu(with Express Card slot) with success, and then I  use this Ubuntu as a target to attack. I use a latest windows 10 x64, then I plug 3380 into the Express Card slot, then run with pcileech.exe testmemread, it always prompted me with error: 
`Memory Test Read: starting, reading 1000 times from address: 0x00000000
Memory Test Read: Failed. DMA failed / data changed by target computer / memory corruption. Read: 1. Run: 0. Offset: 0x282`
I also tried a macos as target to retrieve password, the os version is 10.11, and also not worked.
Could you see what's wrong with it?

**Comment by ufrisk** [comment]
I don't know if this is your problem, but some hardware behaves badly with the USB3380. Unfortunately I do not have such a hardware myself so it's very hard for me to look further into it, but I had other reports of it here on github.

About macOS, if you are thinking about the macOS FileVault2 password recovery Apple patched it in December 2016 (or early 2017 depending on model). If you patched your macOS El Capitan after that date the issue is already patched by Apple.

**Comment by Puzzor** [comment]
It is really strange, I will try a new hardware and update this issue when I have the result.
