### ISSUE TITLE
pci screamer issus

### ISSUE THREAD

**Issue by xyca23** [ufrisk/pcileech#47]
hello, 

i always get this error

FPGA: ERROR: Unable to retrieve required Device PCIe ID [0,v0.0,0000]
PCILEECH: Failed to connect to the device.

when i press the on-board button marked SW3 -> LD1 lights up

LD2 is on 

if i try -> pcileech.exe dump -v;  i get this error(FPGA: ERROR: Unable to retrieve required Device PCIe ID [0,v0.0,0000]
PCILEECH: Failed to connect to the device.) 

 LD1 goes on and stay on

**Comment by ufrisk** [comment]
This is indicative of a successful flash, successful PCIe link but no USB link.

Can you please check that your USB cable is connected properly between the PCIeScreamer and your computer running pcileech?

**Comment by xyca23** [comment]
when i pugin the USB cable windows detect the device and installs the "FTDI FT601 USB 3.0 Bridge Device"
driver.  It shows up in the device manager

**Comment by ufrisk** [comment]
The output [0,v0.0,0000] is indicative of a problem in communicating with the FPGA board, or a wrong flash. If the USB communication was working it would show the bitstream version in that text.

Now I don't believe the flash is wrong since it seems to light up the LD1 when you press the SW3 button (which is a small text I programmed into it).

LD3 should be on at all times. That is normal.

I also assume you downloaded and put the FTD3XX.dll in the same folder as pcileech since it would give another error message otherwise.

**Comment by xyca23** [comment]
The card was broken. Got a new one. Now it works

**Comment by ufrisk** [comment]
I'm glad the issue is resolved. Thanks for letting me know. Good luck with your DMA attacking.
