### ISSUE TITLE
Issue loading kernel module on Ubuntu 16.04

### ISSUE THREAD

**Issue by jeroen-80** [ufrisk/pcileech#8]
Tested v1.1 on Ubuntu 16.04.1 LTS desktop (x64), system with 16GB RAM. Vanilla kernel 4.4.0-31-generic #50: 

```
C:\Users\bofh\Desktop\PCI Leech\pcileech-master\pcileech_files>pcileech.exe kmdload -kmd LINUX_X64

KMD: Failed. Signature found but unable write #2.
PCILEECH: Failed to load kernel module.
```

Latest kernel 4.4.0-36-generic #55:

```
C:\Users\bofh\Desktop\PCI Leech\pcileech-master\pcileech_files>pcileech.exe kmdload -kmd LINUX_X64

KMD: Failed. Error locating generic linux kernel signature.
PCILEECH: Failed to load kernel module.
```

**Comment by ufrisk** [comment]
Not all variations of Linux will work with the built in Linux signature. I've tested it against Ubuntu though and I believe it should work.

The first error indicates there was an error in reading/writing to the memory after the signature was found. Please try to re-insert the card and try again to see if it makes a difference. Things like that happens sometimes.

I'll try to have a closer look at it next week to see if I can find something.

**Comment by jeroen-80** [comment]
I tried reinserting the ExpressCard, with and without reboots, on 16.04.1 LTS with the default kernel. All tries result in the same message: Signature found but unable write #2.

**Comment by ufrisk** [comment]
Thank you for the feedback. I'll look closer into the matter this weekend or early next week. I can't find any obvious bugs in the code; but I'll change it so that it will retry the write if it fails. That helps sometimes. Since the signature is found - but not written I don't believe it's due to your ubuntu version (unless they started using the iommu in that way, which I don't think is the case).

**Comment by ufrisk** [comment]
I tested the LINUX_X64 signature on "Ubuntu 16.04.1 LTS desktop (x64)" 8GB RAM - kernel 4.4.0-31-generic and 4.4.0-36-generic on two of my test laptops and it works.

I believe the issue may be related to pcileech having problem reading and/or updating some memory; which may lead to bit-errors and/or the card becoming unusable until it's power cycled. I've experienced that on some hardware previously.

Now that being said I changed the read/write algorithms in some places to retry if there is a failure. Are you able to check if there is an improvement with the most recent pcileech binary that I just pushed to Github?

**Comment by jeroen-80** [comment]
Tested PCI leech latest GIT version on Ubuntu 16.04.1 LTS desktop (x64), system with 16GB RAM. Vanilla kernel 4.4.0-31-generic #50: 
```
F:\pcileech-master\pcileech_files>pcileech.exe kmdload -kmd LINUX_X64

KMD: Failed. Error locating generic linux kernel signature.
PCILEECH: Failed to load kernel module.
```
One thing worth mentioning: it took quite some time - minutes - for pcileech to finish. Using v1.0/1.1, the error message "Signature found but unable write #2" popped up almost instantly.

Would it be useful for you if I remove some RAM from the system?

**Comment by jeroen-80** [comment]
Just tested another laptop with 4GB RAM. Tested PCI leech latest GIT version on Ubuntu 16.04.1 LTS desktop (x64). Vanilla kernel 4.4.0-31-generic #50. Same result.

**Comment by jeroen-80** [comment]
1.2 on 16GB laptop running Ubuntu 16.04, vanilla kernel 4.4.0-31-generic #50:
```
E:\pcileech\latest\pcileech_files>pcileech.exe kmdload -kmd LINUX_X64

KMD: Failed. Error locating generic linux kernel signature.
PCILEECH: Failed to load kernel module.
```

**Comment by ufrisk** [comment]
sish; I'm pretty much out of options with regards to this one. I'll look closer into it again by trying it on with that exact kernel on my new NUC with 32GB later this week, but I'm almost 100% sure that it won't give me any errors.

It's very hard for me to find the error (if it's a coding error not due to hardware) if it's working for me all the time. I'll keep looking though and keep you updated about the result.

The Windows issue is also interesting; but at least one of the ways into Windows seems to be working for you there.

**Comment by ufrisk** [comment]
I added some features for increased stability when running in usb2 mode. I'm not sure it will help in this case; but it might be worth a try. ` pcileech.exe kmdload -kmd linux_x64 -usb2 ` It will be slower than running in super speed usb3 mode.

**Comment by ufrisk** [comment]
closing issue due to old age. unfortunately pcileech will fail on some hardware for unknown hardware reasons.
